#!/usr/bin/env python

import os, curses

from core import panel
from setup import setupController

# fix 1 second pause delay when pressing ESC
if not os.getenv("ESCDELAY"): os.putenv("ESCDELAY", "25")

def main(stdscr):
    curses.delay_output(25)
    setupController.SetupController(stdscr).start()
  
if __name__ == '__main__':
    try:
        curses.wrapper(main)
    except KeyboardInterrupt:
        # Skip printing stack trace in case of keyboard interrupt. The
        # HALT_ACTIVITY attempts to prevent daemons from triggering a curses redraw
        # (which would leave the user's terminal in a screwed up state). There is
        # still a tiny timing issue here (after the exception but before the flag
        # is set) but I've never seen it happen in practice.
        
        panel.HALT_ACTIVITY = True
        # shutdownDaemons()